// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/13/2026, 6:43:34 PM
const configMerger = require("/Users/icon/ico/polyscore/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/icon/ico/polyscore/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/polyscore/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/polyscore/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/polyscore/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/polyscore/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/polyscore/plugins/**/*.{js,ts,mjs}","/Users/icon/ico/polyscore/composables/**/*.{js,ts,mjs}","/Users/icon/ico/polyscore/utils/**/*.{js,ts,mjs}","/Users/icon/ico/polyscore/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/polyscore/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/polyscore/app.config.{js,ts,mjs}"] }));

module.exports = config
